### ISSUE TITLE
General - Yaml Settings Documentation

### ISSUE THREAD

**Issue by nathankitchen** [Trustmarque/cloudmarque-azure-pwsh#169]
Based on defined schemas for the YAML input files we need to create example documentation for each file. This can then be published to the Docs website as part of standard build processes.

 - [x] Complete #163 so that we have some source schema files!
 - [x] Enhance the pipeline with a new step to extract schema files and generate Markdown/YAML files into the CmdLet documentation artefact. Suggest trying [jsonschema2md](https://github.com/adobe/jsonschema2md/tree/main/examples) with the YAML flag as the first attempt at this (it'll need a NodeJS task in the pipeline).
 - [x] Modify the Docs pipeline to drop the documentation into the appropriate folder before Jekyll runs to generate HTML.
 - [x] Correct any formatting issues.

**Comment by tm-luke** [comment]
Completed with release 1.0.9
