### ISSUE TITLE
New-CmAzCoreMonitor - Action Group Types

### ISSUE THREAD

**Issue by JBiasilloTM** [Trustmarque/cloudmarque-azure-pwsh#190]
New-CmAzCoreMonitor - Action Group Types support "endpoints" such as functions, logic apps, web hooks, email etc.

How far integration testing gone in terms of testing each of Action Group Type supported endpoints?

**Comment by nathankitchen** [comment]
Yes, we use several of these internally. There are a couple like the ITSM connector that we've not been able to test, but all of them are piggybacking off standard ARM templates. If you encounter an issue configuring one of them then please raise a specific issue and we'll be glad to take a look at it.
