### ISSUE TITLE
 Get-CmAzService - single subscription service location

### ISSUE THREAD

**Issue by JBiasilloTM** [Trustmarque/cloudmarque-azure-pwsh#197]
Get-CmAzService service locator searches in current subscription.  

This will be an issue for multi-subscription deployments that want to reuse hub shared services such as log analytics  for "single  pane of glass".

**Comment by nathankitchen** [comment]
We aim to treat each subscription as a self-contained management unit, allowing us to compose broader services using a collection of subscriptions. As a result we'd look to deploy an instance of Log Analytics into each subscription, each configured with its own settings for monitoring, alerts, action groups, etc.

The more independent the subscriptions are, the easier they are to change. A 1-to-1 mapping to a source code (either a repo or a folder within one), a pipeline, and the subscription reduces (if not eliminates) the need to centrally coordinate change. There's also no real cost saving for avoiding the duplication as most Core services are either very cheap or consumption-based.

Queries can be executed over multiple Log Analytics (and Insights) workspaces for wider-scale triage/debugging. Where Workbooks or Solutions are deployed these form a common set of dashboards that can be evolved independently within the context of each subscription, which tends to make most sense from a management perspective.

This is a design limitation that may be worth revisiting once the framework is more mature, but for now it's one that makes it a little harder to deploy spaghetti.
