### ISSUE TITLE
New-CmAzIaasNetworking - deployments not timestamp

### ISSUE THREAD

**Issue by JBiasilloTM** [Trustmarque/cloudmarque-azure-pwsh#199]
Suggested timestamping deployment names to make then unique so as to preserve deployment history / traceability and avoid this type of error. Deep suggested this is a known issue but raising just incase.

InvalidDeploymentLocation - Long running operation failed with status 'Failed'. Additional Info:'Invalid deployment location 'UK West'. The deployment
     | 'Cm_network_resource_group_deployment' already exists in location 'uksouth'.'

**Comment by nathankitchen** [comment]
The uniqueness of deployment names has been addressed in #209, which is now using the name generator. Closing as a duplicate.
