### ISSUE TITLE
New-CmAzIaasNetworking - "Invalid resource group location" if existing NetworkWatcherRG in different region to VNET.NSG

### ISSUE THREAD

**Issue by JBiasilloTM** [Trustmarque/cloudmarque-azure-pwsh#201]
New-CmAzIaasNetworking fails if there's an existing NetworkWatcherRG in different region to Cloudmarque VNET.NSG deployment. E.g. when deploying an new VNET into UK South with an existing NetworkWatcherRG was in west europe the following failure happens:
- Invalid resource group location 'uksouth'. The Resource group already exists in location 'westeurope'. StatusCode: 409 ReasonPhrase: Conflict OperationID

This would be an issue in a brownfield deployment where its not possible to delete the existing network watcher RG.

Suggest testing for NetworkWatcherRG (example below) first (or using cm-service or another tag for Network Watcher RG).  The code below assumes deployments follow the default NetworkWatcherRG name although some engineers / consultants have suggested they deploy network watcher into existing network RG?

Get-AzResourceGroup -Name $networkWatcherResourceGroupName -ErrorVariable rgNotPresent -ErrorAction SilentlyContinue | Out-Null
if ($rgNotPresent) { 
	Write-Verbose "Create new Network Watcher Resource Group: $($networkWatcherResourceGroupName) ..."
	New-AzResourceGroup -Location $workspace.location -Name $networkWatcherResourceGroupName -Force
}
else {
	Write-Verbose "Reuse existing Network Watcher Resource Group: $($networkWatcherResourceGroupName)"
}

**Comment by tm-luke** [comment]
Fixed  in 1.0.10
