### ISSUE TITLE
New-CmAzIaasNetworking - Space in Region causes deployment failure (NetworkWatcher_UK South)

### ISSUE THREAD

**Issue by JBiasilloTM** [Trustmarque/cloudmarque-azure-pwsh#202]
Space in VNET region causes the error below when deploying NetworkWatcher.  removing space fixes the issue but perhaps the code should validate or remove space from region?

 12:45:33 - The deployment 'Cm_New-CmAzIaasNetworking.Nsgs-20210128T124511' failed with error(s). Showing 1 out of 1 error(s). Status Message: At least one resource deployment operation failed.
     | Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details. (Code: DeploymentFailed)  - {   "error": {     "code": "InvalidResourceName",
     | "message": "Resource name NetworkWatcher_UK South is invalid.

**Comment by nathankitchen** [comment]
@tm-luke Did you mean to close this?

**Comment by tm-luke** [comment]
No i think i reopened as the issue wasnt quite addressed.

**Comment by nathankitchen** [comment]
Please could you make a comment describing what's outstanding so that we can get this planned into a milestone? It sounds like a reasonably quick fix that could go into 1.0.11. Assign it back to me when you're done and I'll figure out where it fits.

**Comment by tm-luke** [comment]
Addressed in release 1.0.10.
