### ISSUE TITLE
New-CmAzIaasNetworking - 	support for service endpoints, subnet delegation (e.g. SQL MI etc), private endpoints 

### ISSUE THREAD

**Issue by JBiasilloTM** [Trustmarque/cloudmarque-azure-pwsh#205]
Requesting support for service endpoints, subnet delegation (e.g. SQL MI etc), private endpoints (including PrivateEndpointNetworkPolicies = "Disabled") as this is required on the last few projects.

Currently the following scripts and YML are used to implement these settings on a VNET deployed by New-CmAzIaasNetworking.

[https://dev.azure.com/tesgcloud/CCoE/_git/CloudmarqueExtensions?path=%2FLevel1-shared%2Fnetwork.deploy.yml](url)
[https://dev.azure.com/tesgcloud/CCoE/_git/CloudmarqueExtensions?path=%2F_extensions%2F_pwsh%2FNew-CmAzIaasNetworking-PostDeploy.ps1](url)
[https://dev.azure.com/tesgcloud/CCoE/_git/CloudmarqueExtensions?path=%2F_extensions%2F_pwsh%2FNew-CmAzIaasNetworking-PreDeploy.ps1](url)

**Comment by eliot-trustm** [comment]
This is actually a more complex problem that first envisaged. 
If a workload is relying on that service endpoint, adding the service endpoint back in post deployment means the connection is unavailable for nearly two minutes which causes the running [backup] job to fail.
I can only imagine this would be critical with SQL workloads where pulling it off the network for a couple of minutes could cause more serious problems.
Any fix to this problem really needs to ensure that the endpoint isn't removed or if it is, it's for a minimal amount of time - which doesn't guarantee that time critical workloads may still not fail.

**Comment by tm-luke** [comment]
Issue addressed in 1.0.13 release.
