### ISSUE TITLE
General - Unique deployment names (from multi-region testing)

### ISSUE THREAD

**Issue by JBiasilloTM** [Trustmarque/cloudmarque-azure-pwsh#209]
**IMPORTANT suggest tagging the deployment name with timestamp/hash + the cloudmarque version (Get-CmAzContext.PackageVersion)**

Add unique timestamp to deployment names to preserve deployment history / traceability and avoid this type of error. Test in two regions to validate fixe works.

Also see New-CmAzIaasNetworking - deployments not timestamp #199 but relates to all commandlets

InvalidDeploymentLocation - Long running operation failed with status 'Failed'. Additional Info:'Invalid deployment location 'UK West'. The deployment
| 'Cm_network_resource_group_deployment' already exists in location 'uksouth'.'

**Comment by nathankitchen** [comment]
Planned solution is to:
  1. Add the ability to use a timestamp in the `Get-CmAzResourceName` cmdlet
  2. Create a new resource type of `deployment` that sets the format of the deployment
      - Format would be name-region-timestamp-hash
      - "Name" would be the Cmdlet name and the `Get-CmAzContext.PackageVersion`
  3. Note the [limits on naming](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules), cap the name at 64 characters.
