### ISSUE TITLE
New-CmAzCoreMonitor - add parameter for data retention

### ISSUE THREAD

**Issue by JBiasilloTM** [Trustmarque/cloudmarque-azure-pwsh#211]
New-CmAzCoreMonitor is hard coded for 90 days.  Add config parameter for retentionInDays (default to 90 days)

**Comment by nathankitchen** [comment]
@deepend-dev / @tm-luke - any chance you can sneak this into 1.0.10? If not, please move it into 1.0.11.

**Comment by tm-luke** [comment]
Yeah i can look at that
