### ISSUE TITLE
New-CmAzMonitorLogAlerts - Stateful Implementation 

### ISSUE THREAD

**Issue by tm-luke** [Trustmarque/cloudmarque-azure-pwsh#297]
Theres a preview feature for log alerts that auto resolves alerts if the query condition is no longer met.
![Capture2](https://user-images.githubusercontent.com/65401878/120462430-d91b0400-c392-11eb-8b4e-99b2256a3c24.PNG)

Add the following to the log alerts arm template:
![Capture](https://user-images.githubusercontent.com/65401878/120460114-bab40900-c390-11eb-829a-2387036cbb45.PNG)

The log alerts arm template needs to be updated to the following version as well:
![Capture1](https://user-images.githubusercontent.com/65401878/120460110-ba1b7280-c390-11eb-9dee-6aee8ac2b6c9.PNG)

Test this new change in own subscription, we want to see the following:

* Does a log alert get re-triggered if the conditions are met after re-running the query (hopefully it doesn't).
* Does a log alert get marked as resolved when the conditions are no longer after re-running the query (hopefully it does).

**Comment by nathankitchen** [comment]
Stale - no longer needed
