### ISSUE TITLE
New-CmAzCoreBillingRule  - Error when recreating a budget with the same name.

### ISSUE THREAD

**Issue by tm-luke** [Trustmarque/cloudmarque-azure-pwsh#316]
When recreating a budget at a later date that the first initial deployment, this error is shown below:

557 | 16:45:27 - The deployment 
558 | 'new-cmazcorebillingrule-prd-1013-2021-06-10T164514' failed 
559 | with error(s). Showing 1 out of 1 error(s). Status Message: 
560 | Start date of budgets cannot be updated. Please delete and 
561 | create a new budget. (Request ID: 
562 | 2f3ba3b4-da7b-41f8-8e73-ef39032a75a0) (Code:400) 
563 | CorrelationId: 120d1093-0781-4ff0-b576-2dd7900a7f02

When creating a budget through the above command, we need to check if a budget exists beforehand. If the budget already exists AND no start date is passed in  (its set to the first of this month), we set the startDate of the new budget being deployed to the existing budget's start date. All other settings are passed into the template as normal.

**Comment by deepend-dev** [comment]
Issue resolved with rest api call as Get-CmAzConsumptionBudget is broken..

https://github.com/Azure/azure-powershell/issues/10149
