### ISSUE TITLE
New-CmAzService - Command to add service location to non Cloudmarque resources.

### ISSUE THREAD

**Issue by deepend-dev** [Trustmarque/cloudmarque-azure-pwsh#335]
Create a command to apply the "cm-service" tag to non Cloudmarque resources so that they can be integrated with Cloudmarque, and service located accordingly.

Example - For Public DNS. New-CmAzService can apply "cm-service" tag to DNS so that CNAME can be added to it for Webapps and Azure Frontdoors

**Comment by tm-luke** [comment]
Closed by #340
