### ISSUE TITLE
Issue with New-CmAzIaasNetworking 

### ISSUE THREAD

**Issue by eliot-trustm** [Trustmarque/cloudmarque-azure-pwsh#69]
When creating a new network using the above command i get the following error:
VERBOSE: Adding UDR = 'udr-snet-vnet-cib-uks-prd-hub1-gatewaysubnet' to RG = 'rg-cib-uks-prd-hub1-network01'
VERBOSE: Adding UDR = 'udr-snet-vnet-cib-uks-prd-hub1-management1' to RG = 'rg-cib-uks-prd-hub1-network01'                                                          ription
VERBOSE: Adding UDR = 'udr-snet-vnet-cib-uks-prd-hub1-servers1' to RG = 'rg-cib-uk-------s-prd-hub1-network01'
VERBOSE: 'rg-cib-uks-prd-hub1-network01' has route tables = '7'
New-CmAzIaasNetworking: The term 'f' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by deepend-dev** [comment]
you can bypass confirmation prompt by running command with -Confirm:$false.

https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/users-requesting-confirmation?view=powershell-7

```powershell
New-CmAzIaasNetworking -VnetCsvFile ./projectroot/vnet.csv -Confirm:$false
```
