### ISSUE TITLE
Documentation - Tidy up command documentation

### ISSUE THREAD

**Issue by nathankitchen** [Trustmarque/cloudmarque-azure-pwsh#85]
The following commands aren't being generated correctly in the [documentation website](https://docs.trustmarque.com/cloudmarque/reference/commands/).

- [x] Get-CmAzContext: component set to "Commmon" (one too many m's!)
- [x] Clear-CmAzContext: component not set (should be "Common")
- [x] Get-CmAzResourceName: component not set (should be "Common")
- [x] Get-CmAzSubscriptionName: component not set (should be "Common")
- [x] New-CmAzCore: component not set (should be "Common")
- [x] New-CmAzCoreKeyVault: component set to "Core." (should not have final full stop)

**Comment by nathankitchen** [comment]
Added the KeyVault command issue with the extra full stop

**Comment by deepend-dev** [comment]
#58 maps to this issue.
